"""empty message

Revision ID: 73e9e591c0c0
Revises: 
Create Date: 2021-04-25 20:21:31.869640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73e9e591c0c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('question', sa.String(length=20), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_score_category'), 'score', ['category'], unique=False)
    op.create_index(op.f('ix_score_level'), 'score', ['level'], unique=False)
    op.create_index(op.f('ix_score_question'), 'score', ['question'], unique=False)
    op.create_index(op.f('ix_score_score'), 'score', ['score'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_score_score'), table_name='score')
    op.drop_index(op.f('ix_score_question'), table_name='score')
    op.drop_index(op.f('ix_score_level'), table_name='score')
    op.drop_index(op.f('ix_score_category'), table_name='score')
    op.drop_table('score')
    op.drop_table('user')
    # ### end Alembic commands ###
